[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyexcuses"
version = "0.0.1"
authors = [
  { name="Joseph Chege", email="jcm9824@nyu.edu" },
  { name="Darren Zou", email="" }
  { name="Peter D'Angelo", email="" }
  { name="Gene Park", email="" }
  { name="Jack Zhang", email="" }
]
description = "Package to fix all your coding problems."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/software-students-fall2024/3-python-package-realoriginal"
Issues = "https://github.com/software-students-fall2024/3-python-package-realoriginal/issues"